GET http://localhost:5057/games

###

GET http://localhost:5057/games/4

###
POST  http://localhost:5057/games
Content-Type: application/json

{
  "Name": "NeVER",
  "genreId": "2",
  "price": 78.9,
  "releaseDate": "2006-04-15"
}



###

PUT http://localhost:5057/games/4
Content-Type: application/json

 {
 "name": "EXOUSIA",
  "genre": "horror",
  
  "releaseDate": "2003-04-15"
}


###

DELETE http://localhost:5057/games/8